### ISSUE TITLE
编译太多时报错：命令行太长

### ISSUE THREAD

**Issue by HESUPING** [nbtool/all_in_one_ide_tool#13]
问题： 工程编译文件较多时，会超过windows终端的长度限制，导致编译的时候报错：命令行太长
解决方案建议：将需要的.h .o文件写入一个专门的文件中，然后gcc编译的时候，直接包含该文件。

**Comment by beautifulzzzz** [comment]
解决由于 .o 和 h路径过多 ，导致命令行过长，导致编译不通过问题，现在将 .o 和路径都放在文件里，编译时引用这个文件，对于编译 .c到.o，默认使用文件，对于link是由用户自己在 vendor.json中配置 的"
[V2.X e01049a] #13 解决由于 .o 和 h路径过多，导致命令行过长，导致编译不通过问题，现在将 .o 和路径都放在文件里，编译时引用这个文件，对于编译 .c到.o，默认使用文件，对于link是由用户自己在 vendor.json中配置的

**Comment by beautifulzzzz** [comment]
LINK 选择用文件方式还是展开方式：

展开方式（老方式，可能会导致命令行过长，超出限制）

```
"ld":"tc32-elf-ld --gc-sections -T $PROJECT_ROOT/vendor/tlsr825x_smesh/sdk/telink_sig_mesh_sdk/boot.link $O_FILES $LIB_DIRS \"-(\" $LIBS \"-)\" -o $ELF",
```

文件方式：

```
 "ld":"tc32-elf-ld --gc-sections -T $PROJECT_ROOT/vendor/tlsr825x_smesh/sdk/telink_sig_mesh_sdk/boot.link @$PROJECT_ROOT/.log/gcc_o.txt  $LIB_DIRS \"-(\" $LIBS \"-)\" -o $ELF",
```

**Comment by beautifulzzzz** [comment]
@HESUPING 已经修复，可以关闭该issue
