### ISSUE TITLE
简化输出的固件

### ISSUE THREAD

**Issue by suding-china** [nbtool/all_in_one_ide_tool#25]
目前输出的固件有如下5个，客户会迷惑，建议修改为OTA和生产两个固件即可
![image](https://user-images.githubusercontent.com/34054129/204980766-38ac860b-d447-421f-8f93-207e6ecc08ed.png)

**Comment by beautifulzzzz** [comment]
目前每个都有作用（比如上传，烧录等，唯一可以去掉的是 QIO，可以在 vendor.json 中去掉那个key-value就行 @suding-china
