### ISSUE TITLE
Wind IDE拉下来的开发包也需要识别配置各个组件里的IOTConfig配置

### ISSUE THREAD

**Issue by jiangxuefeng2023** [nbtool/all_in_one_ide_tool#42]
当前，Wind IDE下运行编译/配置指令时，只有APP的配置。 实际门锁许多组件都有自己的IOTConfig配置项。如果将这些配置项移到APP里并不合适，因为如果没有选择某个组件，也要在APP里配置这个组件的配置项，是不必要的

**Comment by beautifulzzzz** [comment]
应用形成 SDK, 对于源码释放的组件，可以将 kconfig 携带：
![image](https://github.com/nbtool/all_in_one_ide_tool/assets/6163589/46f16e7d-7fb2-408d-b1ec-ae5875d2aef6)

但是基线源码释放的组件， kconfig 没有携带，其在各个子类的 _tlib 中分别实现

**Comment by beautifulzzzz** [comment]
需要应用组件具备kconfig功能

**Comment by beautifulzzzz** [comment]
#203302297367621bc7ad5b005dafbe0401d017ad  已经实现应用层组件、驱动、应用层本身的组件支持 kconfig，需要注意，开源的组件的 local.mk 中不要用 find，因为 find 在 windows 上存在兼容问题。local.mk 模板见：https://github.com/nbtool/all_in_one_ide_tool/blob/V2.X/docs/01-tag_support_app_package.md
